import React, { useRef } from 'react';
import { FileText, Printer, Copy, Share2, Info } from 'lucide-react';
import { formatRupiah } from '../lib/utils';
import { AppData } from '../types';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

type ReportProps = {
  data: AppData;
  calculations: any;
};

export const Report: React.FC<ReportProps> = ({ data, calculations }) => {
  const reportRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    window.print();
  };

  const exportPDF = async () => {
    if (!reportRef.current) return;
    const canvas = await html2canvas(reportRef.current, { scale: 2 });
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
    pdf.save(`Laporan-HPP-${data.production.productName}.pdf`);
  };

  const copySummary = () => {
    const summary = `RINGKASAN HPP - ${data.production.productName}
HPP per Unit: ${formatRupiah(calculations.hppPerUnitFinal)}
Total Produksi: ${calculations.unitsPerMonth} unit/bulan
Total Biaya: ${formatRupiah(calculations.totalCostPerMonth)}/bulan
Generated by CostMaster Pro`;
    navigator.clipboard.writeText(summary);
    alert('Ringkasan disalin!');
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between no-print">
        <h2 className="text-2xl font-bold">Laporan & Analisis Akhir</h2>
        <div className="flex gap-2">
          <button onClick={handlePrint} className="btn-primary bg-slate-700 text-white hover:bg-slate-600">
            <Printer className="w-4 h-4" /> Cetak
          </button>
          <button onClick={exportPDF} className="btn-primary">
            <Share2 className="w-4 h-4" /> Export PDF
          </button>
          <button onClick={copySummary} className="btn-primary bg-accent-secondary text-white">
            <Copy className="w-4 h-4" /> Copy Ringkasan
          </button>
        </div>
      </div>

      <div ref={reportRef} className="bg-white text-slate-900 rounded-xl p-12 shadow-2xl space-y-10 min-h-[1000px] border border-slate-200">
        <header className="flex justify-between items-start border-b-2 border-accent-primary pb-8">
           <div className="space-y-2">
              <h1 className="text-3xl font-black text-accent-primary uppercase tracking-tighter">CostMaster Pro</h1>
              <p className="text-slate-500 font-medium">Laporan Analisis Harga Pokok Produksi</p>
           </div>
           <div className="text-right space-y-1">
              <h2 className="text-xl font-bold">Laporan #{Math.floor(Math.random()*10000)}</h2>
              <p className="text-sm text-slate-500">Tanggal: {new Date().toLocaleDateString('id-ID')}</p>
           </div>
        </header>

        <section className="space-y-4">
           <h3 className="text-lg font-bold border-l-4 border-accent-primary pl-3 bg-accent-primary/5 py-1">1. Ringkasan Eksekutif</h3>
           <p className="text-slate-700 leading-relaxed text-sm">
              Analisis HPP untuk produk <span className="font-bold">"{data.production.productName}"</span> menunjukkan bahwa biaya produksi per unit adalah <span className="font-bold text-accent-secondary">{formatRupiah(calculations.hppPerUnitFinal)}</span>. 
              Dengan kapasitas produksi bulanan sebesar <span className="font-bold">{calculations.unitsPerMonth} unit</span>, total biaya operasional yang harus disiapkan 
              adalah <span className="font-bold">{formatRupiah(calculations.totalCostPerMonth)}</span>. 
              Target pengembalian modal (ROI) diprediksi tercapai dalam <span className="font-bold">{ (data.investments.reduce((acc,i)=>acc+i.value,0) / ((calculations.hppPerUnitFinal * 1.5) - calculations.hppPerUnitFinal) / calculations.unitsPerMonth).toFixed(1) } bulan</span> pada harga jual retail standard (markup 50%).
           </p>
        </section>

        <div className="grid grid-cols-2 gap-10">
           <section className="space-y-4">
              <h3 className="text-lg font-bold border-l-4 border-accent-primary pl-3">2. Struktur Biaya Utama</h3>
              <table className="w-full text-xs text-left border-collapse">
                 <thead className="bg-slate-50 border-y border-slate-200">
                    <tr>
                       <th className="p-3">Kategori</th>
                       <th className="p-3 text-right">Nilai / Unit</th>
                       <th className="p-3 text-right">%</th>
                    </tr>
                 </thead>
                 <tbody className="divide-y divide-slate-100">
                    <tr><td className="p-3">Bahan Baku</td><td className="p-3 text-right">{formatRupiah(calculations.materialPerUnit)}</td><td className="p-3 text-right">{(calculations.materialPerUnit / calculations.hppPerUnitFinal * 100).toFixed(1)}%</td></tr>
                    <tr><td className="p-3">Tenaga Kerja</td><td className="p-3 text-right">{formatRupiah(calculations.laborPerUnit)}</td><td className="p-3 text-right">{(calculations.laborPerUnit / calculations.hppPerUnitFinal * 100).toFixed(1)}%</td></tr>
                    <tr><td className="p-3">Overhead</td><td className="p-3 text-right">{formatRupiah(calculations.overheadPerUnit)}</td><td className="p-3 text-right">{(calculations.overheadPerUnit / calculations.hppPerUnitFinal * 100).toFixed(1)}%</td></tr>
                    <tr><td className="p-3">Non-Produksi</td><td className="p-3 text-right">{formatRupiah(calculations.nonProductionPerUnit)}</td><td className="p-3 text-right">{(calculations.nonProductionPerUnit / calculations.hppPerUnitFinal * 100).toFixed(1)}%</td></tr>
                    <tr className="font-bold bg-slate-50"><td className="p-3">Total HPP Akhir</td><td className="p-3 text-right">{formatRupiah(calculations.hppPerUnitFinal)}</td><td className="p-3 text-right">100%</td></tr>
                 </tbody>
              </table>
           </section>

           <section className="space-y-4">
              <h3 className="text-lg font-bold border-l-4 border-accent-primary pl-3">3. Daftar Harga Jual</h3>
              <div className="space-y-2">
                 {data.priceLevels.map(l => (
                   <div key={l.id} className="flex justify-between items-center p-3 bg-slate-50 rounded border border-slate-200">
                      <div>
                        <p className="text-xs font-bold uppercase text-slate-500">{l.name}</p>
                        <p className="text-xs">Min. Order: {l.minOrder} unit</p>
                      </div>
                      <div className="text-right">
                         <p className="text-lg font-black text-accent-secondary">{formatRupiah(calculations.hppPerUnitFinal * (1 + l.markupPercent/100))}</p>
                         <p className="text-[10px] text-emerald-600 font-bold">Margin: {l.markupPercent}%</p>
                      </div>
                   </div>
                 ))}
              </div>
           </section>
        </div>

        <section className="space-y-4 border-t border-slate-200 pt-8">
           <h3 className="text-lg font-bold border-l-4 border-accent-danger pl-3">4. Rekomendasi Bisnis</h3>
           <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 text-sm italic text-slate-800 leading-loose">
              {calculations.materialPerUnit / calculations.hppPerUnitFinal > 0.6 ? 
                "• Perhatian: Biaya bahan baku melebihi 60% dari HPP. Cobalah mencari supplier alternatif atau negosiasi harga grosir." : 
                "• Efisiensi bahan baku sudah baik."}
              <br />
              {calculations.laborPerUnit / calculations.hppPerUnitFinal > 0.2 ? 
                "• Biaya tenaga kerja cukup tinggi. Pertimbangkan penggunaan mesin atau otomatisasi untuk meningkatkan output per jam." : 
                "• Kontribusi upah terhadap harga sudah ideal."}
              <br />
              • Untuk mencapai BEP lebih cepat, fokus pada penjualan level 'Grosir Kecil' ke atas untuk meningkatkan volume per transaksi.
              <br />
              • Pertahankan utilisasi produksi di atas 70% untuk menekan kontribusi biaya tetap terhadap HPP.
           </div>
        </section>

        <footer className="text-center text-[10px] text-slate-400 pt-10">
           Dokumen ini dihasilkan secara otomatis oleh sistem CostMaster Pro. Sertifikasi keakuratan perhitungan bergantung pada keandalan data input.
        </footer>
      </div>
    </div>
  );
};
